function qs(s){return document.querySelector(s)}
function qsa(s){return Array.from(document.querySelectorAll(s))}
function applyTheme(isDark){document.body.classList.toggle('light',!isDark);localStorage.setItem('theme',isDark?'dark':'light')}
(function(){var t=localStorage.getItem('theme')||'dark';applyTheme(t!=='light')})()
qsa('#theme-toggle').forEach(b=>b.addEventListener('click',()=>{applyTheme(!document.body.classList.contains('light'))}))
document.addEventListener('DOMContentLoaded',function(){
  qsa('.progress-bar').forEach(el=>{var v=el.getAttribute('data-fill')||0;setTimeout(()=>el.style.width=v+'%',120)})
  var clock=qs('#digital-clock'),sess=qs('#session-timer');if(clock&&sess){function p(n){return String(n).padStart(2,'0')}function u(){var d=new Date();clock.textContent=p(d.getHours())+':'+p(d.getMinutes())+':'+p(d.getSeconds())}u();setInterval(u,1000);var secs=parseInt(sessionStorage.getItem('session_secs')||'0',10),tick=null;function upd(){var h=Math.floor(secs/3600),m=Math.floor((secs%3600)/60),s=secs%60;sess.textContent='Viewed: '+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');sessionStorage.setItem('session_secs',secs)}function start(){if(tick)return;tick=setInterval(()=>{secs+=1;upd()},1000)}function stop(){if(tick){clearInterval(tick);tick=null}}if(document.visibilityState==='visible')start();upd();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')start();else stop()});window.addEventListener('beforeunload',()=>{stop();localStorage.setItem('last_view_secs',secs)})}
  var form=qs('#contact-form');if(form){form.addEventListener('submit',function(e){e.preventDefault();var n=qs('#name').value.trim(),em=qs('#email').value.trim(),m=qs('#message').value.trim(),err=qs('#form-error');if(n.length<2){err.textContent='Enter name';return}if(!/^\S+@\S+\.\S+$/.test(em)){err.textContent='Enter valid email';return}if(m.length<10){err.textContent='Message too short';return}err.textContent='';alert('Message sent (simulation)');form.reset()})}
  var filters=qsa('.filter-btn');var projects=qsa('.project-card');filters.forEach(f=>f.addEventListener('click',function(){filters.forEach(x=>x.classList.remove('active'));this.classList.add('active');var val=this.getAttribute('data-filter');projects.forEach(p=>{p.style.display=(val==='all'||p.getAttribute('data-tech')===val)?'flex':'none'})}))
  var sortBtn=qs('#sort-title');if(sortBtn){sortBtn.addEventListener('click',function(){var grid=qs('#projects-grid');var items=Array.from(grid.children);items.sort((a,b)=>a.querySelector('h3').innerText.localeCompare(b.querySelector('h3').innerText));items.forEach(i=>grid.appendChild(i))})}
})()